### ISSUE TITLE
Error on Powershell

### ISSUE THREAD

**Issue by BanCrash** [irliao/netgear-ex8000-restart#1]
Hello! First thanks you for this code, I just test it and it works like a charm!

But even with the adapter restarted, an error arises on powershell:

> (node:17380) UnhandledPromiseRejectionWarning: Error: Navigation Timeout Exceeded: 30000ms exceeded
>     at Promise.then (D:\Netgear Ex8000 Restart\node_modules\puppeteer\lib\NavigatorWatcher.js:73:21)
> (node:17380) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:17380) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I don't know what is the meaning of this, so I just let you know about this.

Again, thanks for the script, I have the same issues and this will help me a lot!

**Comment by irliao** [comment]
Hi @BanCrash, sorry for my late reply... been less active in GitHub due to work.

I will try to update the project with a fix for the exceptions in the near future.

Thank you so much for the feedback!

**Comment by BanCrash** [comment]
Sure, no problem, thanks you for replying!

Perfect, thank you!

**Comment by irliao** [comment]
Hi @BanCrash , I finally got around to working on this repository again (sorry again for the delay). I have put in a fix to hopefully resolve the issue with a couple of enhancements. Please let me know if this is still an issue for you. Thank you!

**Comment by BanCrash** [comment]
Hello, thanks you so much! I just tested and it doesn't show any error any more. So this is fixed now, thanks you for fixing this!

Regards.
